#! /bin/sh

# Startup
picom -b &
killall sxhkd; sxhkd &
killall dunst; dunst &
feh --bg-fill $HOME/Pictures/wallpaper.png &
setxkbmap -option grp:alt_shift_toggle us,th &
$HOME/.config/polybar/launch.sh

# Workspaces
if [[ $(xrandr -q | grep 'HDMI-0 connected') ]]
then
  bspc monitor "HDMI-0" -d 1 2 3 4
  bspc monitor "DP-4" -d 5 6 7 8
else
  bspc monitor "DP-4" -d 1 2 3 4 5 6 7 8
fi

# Configurations
bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false

##############################################################

#pgrep -x sxhkd > /dev/null || sxhkd & polybar example &

#bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config border_width         2
#bspc config window_gap          12

#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
