local icondir = ""
local fadir = ""

icondir = theme_path .. "icons/"
fadir = theme_path .. "icons/fontawesome/png40/"

theme.widget_ac                                 = icondir .. "ac.png"
theme.widget_battery                            = icondir .. "battery.png"
theme.widget_battery_low                        = icondir .. "battery_low.png"
theme.widget_battery_empty                      = icondir .. "battery_empty.png"
theme.widget_mem                                = icondir .. "memory.png"
theme.widget_clock                              = icondir .. "clock-solid.svg"
theme.widget_cpu                                = icondir .. "cpu.png"
theme.widget_temp                               = icondir .. "temp.png"
theme.widget_net                                = icondir .. "net.png"
theme.widget_hdd                                = icondir .. "hdd.png"
theme.widget_music                              = icondir .. "note.png"
theme.widget_music_on                           = icondir .. "note_on.png"
theme.widget_vol                                = icondir .. "vol.png"
theme.widget_vol_low                            = icondir .. "vol_low.png"
theme.widget_vol_no                             = icondir .. "vol_no.png"
theme.widget_vol_mute                           = icondir .. "vol_mute.png"
theme.widget_mail                               = icondir .. "mail.png"
theme.widget_mail_on                            = icondir .. "mail_on.png"