[tools]
node = "lts"
go = "latest"
bun = "latest"
gemini-cli = "latest"
uv = "latest"
zig = "master"
zls = "master"
opencode = "latest"
claude = "latest"

[env]

[tasks]

[settings]

[plugins]
zls = "https://github.com/mzwallow/mise-zls"
