[tools]
node = "lts"
go = "latest"
bun = "latest"
gemini-cli = "latest"
uv = "latest"
zig = "0.16.0"
zls = "0.16.0"
opencode = "latest"
claude = "latest"
rust = "latest"

[env]

[tasks]

[settings]

[plugins]
zls = "https://github.com/mzwallow/mise-zls"
